version: "3.9"

services:
  models_re_ner:
    env_file:
      - .env
    container_name: models_analize
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        S3_ACCESS_KEY: ${S3_ACCESS_KEY}
        S3_SECRET_KEY: ${S3_SECRET_KEY}
    ports:
      - "8986:8989"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #Change desktop to 1 (when one graphics card is present) 
              count: 2
              capabilities: [gpu]    
#  nginx:

